name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BASE_DIR: /srv/leadforce
      TARGET_DIR: /srv/leadforce/app
      SERVICE_NAME: leadforce
      SERVICE_USER: leadforce

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare VPS directories
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            set -euo pipefail
            sudo useradd -r -m -d "$BASE_DIR" -s /usr/sbin/nologin "$SERVICE_USER" 2>/dev/null || true
            sudo mkdir -p "$BASE_DIR" "$TARGET_DIR" "$BASE_DIR/logs" "$BASE_DIR/run"
            sudo python3 -m venv "$BASE_DIR/venv" || true
            sudo chown -R "$SERVICE_USER":"$SERVICE_USER" "$BASE_DIR"
            sudo chmod -R u=rwX,g=rX,o= "$BASE_DIR"
            sudo touch "$BASE_DIR/logs/gunicorn.access.log" "$BASE_DIR/logs/gunicorn.error.log"
            sudo chown -R "$SERVICE_USER":"$SERVICE_USER" "$BASE_DIR/logs"

      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          source: .
          target: ${{ env.TARGET_DIR }}
          strip_components: 0
          rm: true

      - name: Run remote deploy script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            cd "$TARGET_DIR"
            chmod +x scripts/deploy.sh
            BASE_DIR="$BASE_DIR" APP_DIR="$TARGET_DIR" SERVICE_NAME="$SERVICE_NAME" SERVICE_USER="$SERVICE_USER" SERVICE_GROUP="$SERVICE_USER" bash scripts/deploy.sh
