name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TARGET_DIR: /root/LeadForcePython
      SERVICE_NAME: leadforce

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare VPS directories
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            mkdir -p "$TARGET_DIR"

      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          source: .
          target: ${{ env.TARGET_DIR }}
          strip_components: 0
          rm: true

      - name: Run remote deploy script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            cd "$TARGET_DIR"
            chmod +x scripts/deploy.sh
            APP_DIR="$TARGET_DIR" SERVICE_NAME="$SERVICE_NAME" PYTHON_BIN=/usr/bin/python3 bash scripts/deploy.sh
